dist: xenial   # required for Python >= 3.7
language: python

services:
  - postgresql

python:
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - python --version

before_script:
  - psql -c 'CREATE DATABASE eventsourcing;' -U postgres
  - psql -c "CREATE USER eventsourcing WITH PASSWORD 'eventsourcing';" -U postgres

install:
  - pip install -U virtualenv
  - virtualenv --python=python ../venv
  - source ../venv/bin/activate
  - which python
  - python --version
  - pip install -U pip
  - pip install -e .[testing]


script:
    make lint test;

after_success:
    coverage combine;
    coveralls;
